# Shared settings and helpers for the cluster scripts (sourced, not run).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
K8S="$ROOT/infra/k8s"

# One kind cluster per role (Stage 7): "central" runs the central services
# and monitoring, each region its Agones and instance servers.
CLUSTERS=(central eu us)
REGIONS=(eu us)
NAMESPACE=mmoexile
cluster_name() { echo "mmoexile-$1"; }       # central → mmoexile-central
context() { echo "kind-mmoexile-$1"; }       # its kubectl context
node_container() { echo "mmoexile-$1-control-plane"; } # its (only) node's container

# Generated by cluster-init.sh, git-ignored
SECRETS="$K8S/.secrets"
secret() { cat "$SECRETS/$1"; }

# The databases next to the cluster (cluster-db-up.sh): Docker containers
# on kind's network, e.g. db_container postgres → mmoexile-db-postgres
DB_NETWORK=kind
db_container() { echo "mmoexile-db-$1"; }
POSTGRES_IMAGE=postgres:16
PGBOUNCER_IMAGE=edoburu/pgbouncer:v1.26.0-p0
REDIS_IMAGE=redis:7
POSTGRES_EXPORTER_IMAGE=prometheuscommunity/postgres-exporter:v0.20.1
PGBOUNCER_EXPORTER_IMAGE=prometheuscommunity/pgbouncer-exporter:v0.12.1
REDIS_EXPORTER_IMAGE=oliver006/redis_exporter:v1.93.0

# A database container's address on kind's network (PgBouncer: Postgres')
db_address() {
  docker inspect -f "{{(index .NetworkSettings.Networks \"$DB_NETWORK\").IPAddress}}" "$(db_container "$1")"
}

# Points a cluster's database Services (overlays/kind-common/databases.yaml,
# overlays/central/databases.yaml) at the containers' current addresses:
# one EndpointSlice per Service. apply_db_endpoints <cluster>
apply_db_endpoints() {
  local cluster=$1 ip_postgres ip_redis
  ip_postgres=$(db_address postgres)
  ip_redis=$(db_address redis)
  {
    # PgBouncer and the Postgres/PgBouncer exporters share Postgres' network
    # namespace (and address), the Redis exporter Redis'
    endpoint_slice pgbouncer "$ip_postgres" postgres 6432
    endpoint_slice redis "$ip_redis" redis 6380
    if [[ "$cluster" == central ]]; then
      endpoint_slice postgres "$ip_postgres" postgres 5432
      endpoint_slice postgres-exporter "$ip_postgres" metrics 9187
      endpoint_slice pgbouncer-exporter "$ip_postgres" metrics 9127
      endpoint_slice redis-exporter "$ip_redis" metrics 9121
    fi
  } | kc "$cluster" apply -f - >/dev/null
  echo "$cluster: pgbouncer → $ip_postgres:6432, redis → $ip_redis:6380$([[ "$cluster" == central ]] && echo ", postgres → $ip_postgres:5432, exporters")"
}
endpoint_slice() {
  cat <<END
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: $1-external
  namespace: $NAMESPACE
  labels:
    kubernetes.io/service-name: $1
    endpointslice.kubernetes.io/managed-by: cluster-db.mmoexile.dev
    app.kubernetes.io/part-of: mmoexile
addressType: IPv4
ports: [{ name: $3, port: $4, protocol: TCP }]
endpoints: [{ addresses: ["$2"], conditions: { ready: true } }]
---
END
}

# Removes kind's Docker network once neither a kind cluster nor another
# container (databases, cloud-provider-kind) uses it
remove_unused_network() {
  docker network inspect "$DB_NETWORK" >/dev/null 2>&1 || return 0
  [[ -z "$(kind get clusters 2>/dev/null)" ]] || return 0
  [[ "$(docker network inspect -f '{{len .Containers}}' "$DB_NETWORK")" == 0 ]] || return 0
  docker network rm "$DB_NETWORK" >/dev/null && echo "Removed Docker network $DB_NETWORK"
}

# True if PgBouncer (as mmoexile_app) and Redis (as mmoexile) answer over
# verified TLS. Passwords go through the environment, not the arguments.
db_ready() {
  PGPASSWORD=$(secret postgres-app-password) docker exec -e PGPASSWORD "$(db_container postgres)" \
    psql "host=localhost port=6432 dbname=mmoexile user=mmoexile_app sslmode=verify-full sslrootcert=/tls/ca.crt" \
    -tAc "select 1" >/dev/null 2>&1 &&
    REDISCLI_AUTH=$(secret redis-password) docker exec -e REDISCLI_AUTH "$(db_container redis)" \
      redis-cli --tls --cacert /tls/ca.crt -p 6380 --user mmoexile ping 2>/dev/null | grep -q PONG
}

# Gives LoadBalancer Services an address on kind's network, like a cloud's
# load balancers (D29): watches every kind cluster and runs an Envoy
# container per LoadBalancer Service. Started by cluster-up.sh, removed by
# cluster-down.sh.
CLOUD_PROVIDER_KIND_IMAGE=registry.k8s.io/cloud-provider-kind/cloud-controller-manager:v0.12.0
CLOUD_PROVIDER_KIND=mmoexile-cloud-provider-kind
CLOUD_PROVIDER_KIND_ENVOY_IMAGE=envoyproxy/envoy:v1.33.2  # pulled by it
# The load balancer containers it started for our clusters (labelled
# "<cluster>/<namespace>/<service>")
load_balancer_containers() {
  docker ps -a --filter label=io.x-k8s.cloud-provider-kind.cluster \
    --format '{{.ID}} {{.Label "io.x-k8s.cloud-provider-kind.cluster"}}' | awk '$2 ~ /^mmoexile/ { print $1 }'
}

# The service mesh (D30): only Linkerd's edge releases are open source
# builds; chart 2026.9.3 = edge-26.9.3. The CLI (linkerd) has the same
# version. Linkerd's policy needs the Gateway API's CRDs (HTTPRoute).
LINKERD_CHART_REPO=https://helm.linkerd.io/edge
LINKERD_VERSION=2026.9.3
LINKERD_CLI_VERSION=edge-26.9.3
GATEWAY_API_VERSION=v1.5.1

AGONES_CHART_REPO=https://agones.dev/chart/stable
AGONES_VERSION=1.61.0
MONITORING_CHART_REPO=https://prometheus-community.github.io/helm-charts
MONITORING_VERSION=91.9.0  # kube-prometheus-stack

# Apps built from node.Dockerfile (plus the "migrate" and "client" images)
APPS=(account-api social orchestrator directory instance-server)
IMAGE_TAG=dev

# kubectl and helm against one of our clusters (never the current
# context): kc eu get pods, hc central list
kc() { local cluster=$1; shift; kubectl --context "$(context "$cluster")" "$@"; }
hc() { local cluster=$1; shift; helm --kube-context "$(context "$cluster")" "$@"; }

step() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
fail() { printf '\033[31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

# `linkerd check` for one cluster: control plane, proxies and extensions;
# prints what failed and returns non-zero. Two of the multicluster checks
# are skipped: they connect from this host to the linked clusters' API
# servers by the names in the Links (the nodes' names on kind's network),
# which only resolve inside the clusters. Shared trust holds by
# construction (every cluster's issuer is signed by our CA), and
# cluster-up.sh waits for the links' gateways instead.
linkerd_check() {
  local result
  # Its own exit code counts the skipped checks too
  result=$(linkerd --context "$(context "$1")" check -o json --wait 2m 2>/dev/null) || true
  node -e '
    const skipped = ["remote cluster access credentials are valid", "clusters share trust anchors"];
    let input = "";
    process.stdin.on("data", (d) => (input += d)).on("end", () => {
      const failed = [];
      // One JSON document for the core checks, one per extension
      for (const doc of input.trim().split(/\n(?=\{)/)) {
        for (const category of JSON.parse(doc).categories) {
          for (const check of category.checks) {
            if (check.result === "error" && !skipped.includes(check.description)) {
              failed.push(`${category.categoryName}: ${check.description}: ${check.error ?? ""}`);
            }
          }
        }
      }
      console.log(failed.length ? failed.join("\n") : "linkerd check: all passed");
      process.exit(failed.length ? 1 : 0);
    });' <<<"$result"
}

# The clusters whose exported Services a cluster mirrors (Linkerd
# multicluster links): central sees the regions' entry points, each region
# sees central's services
linked_clusters() {
  case "$1" in
    central) echo "${REGIONS[@]}" ;;
    *) echo central ;;
  esac
}

cluster_exists() { kind get clusters 2>/dev/null | grep -qx "$(cluster_name "$1")"; }
require_clusters() {
  for cluster in "${CLUSTERS[@]}"; do
    cluster_exists "$cluster" || fail "No cluster $(cluster_name "$cluster") (pnpm cluster:up)"
  done
}

# Runs "<function> <cluster>" for several clusters at once, each line of
# output prefixed with the cluster; fails if any of them failed.
# for_clusters <function> <cluster>...
for_clusters() {
  local fn=$1 pids=() cluster failed=0
  shift
  for cluster in "$@"; do
    ( set -o pipefail; "$fn" "$cluster" 2>&1 | sed -u "s/^/[$cluster] /" ) &
    pids+=($!)
  done
  for pid in "${pids[@]}"; do wait "$pid" || failed=1; done
  (( failed == 0 )) || fail "$fn failed (see above)"
}

image() { echo "mmoexile/$1:$IMAGE_TAG"; }

# Builds one image from the repository: an app, "migrate" or "client"
build_image() {
  local name=$1
  case "$name" in
    client) docker build -q -f "$ROOT/infra/docker/client.Dockerfile" -t "$(image client)" "$ROOT" ;;
    migrate) docker build -q -f "$ROOT/infra/docker/node.Dockerfile" --target migrate -t "$(image migrate)" "$ROOT" ;;
    *) docker build -q -f "$ROOT/infra/docker/node.Dockerfile" --build-arg "APP=$name" -t "$(image "$name")" "$ROOT" ;;
  esac >/dev/null
}

# Loads images into a cluster: load_images <cluster> <image>...
# (kind skips images the node already has in the same version)
load_images() {
  local cluster=$1
  shift
  kind load docker-image --name "$(cluster_name "$cluster")" "$@" 2>&1 | grep -vE "not yet present|already present" || true
}
# The images a cluster runs (built from the repository)
cluster_images() {
  case "$1" in
    central) for name in migrate account-api social orchestrator directory client; do image "$name"; done ;;
    *) image instance-server ;;
  esac
}
