# Shared settings and helpers for the cluster scripts (sourced, not run).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
K8S="$ROOT/infra/k8s"

CLUSTER=mmoexile
CONTEXT="kind-$CLUSTER"
NAMESPACE=mmoexile

# Generated by cluster-init.sh, git-ignored
SECRETS="$K8S/.secrets"
secret() { cat "$SECRETS/$1"; }

# The databases next to the cluster (cluster-db-up.sh): Docker containers
# on kind's network, e.g. db_container postgres → mmoexile-db-postgres
DB_NETWORK=kind
db_container() { echo "mmoexile-db-$1"; }
POSTGRES_IMAGE=postgres:16
PGBOUNCER_IMAGE=edoburu/pgbouncer:v1.26.0-p0
REDIS_IMAGE=redis:7
POSTGRES_EXPORTER_IMAGE=prometheuscommunity/postgres-exporter:v0.20.1
PGBOUNCER_EXPORTER_IMAGE=prometheuscommunity/pgbouncer-exporter:v0.12.1
REDIS_EXPORTER_IMAGE=oliver006/redis_exporter:v1.93.0

# A database container's address on kind's network (PgBouncer: Postgres')
db_address() {
  docker inspect -f "{{(index .NetworkSettings.Networks \"$DB_NETWORK\").IPAddress}}" "$(db_container "$1")"
}

# Points the cluster's database Services (overlays/kind/databases.yaml) at
# the containers' current addresses: one EndpointSlice per Service
apply_db_endpoints() {
  local ip_postgres ip_redis
  ip_postgres=$(db_address postgres)
  ip_redis=$(db_address redis)
  {
    # PgBouncer and the Postgres/PgBouncer exporters share Postgres' network
    # namespace (and address), the Redis exporter Redis'
    endpoint_slice pgbouncer "$ip_postgres" postgres 6432
    endpoint_slice postgres "$ip_postgres" postgres 5432
    endpoint_slice redis "$ip_redis" redis 6380
    endpoint_slice postgres-exporter "$ip_postgres" metrics 9187
    endpoint_slice pgbouncer-exporter "$ip_postgres" metrics 9127
    endpoint_slice redis-exporter "$ip_redis" metrics 9121
  } | k apply -f - >/dev/null
  echo "pgbouncer → $ip_postgres:6432, postgres → $ip_postgres:5432, redis → $ip_redis:6380 (exporters: 9187, 9127, 9121)"
}
endpoint_slice() {
  cat <<END
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: $1-external
  namespace: $NAMESPACE
  labels:
    kubernetes.io/service-name: $1
    endpointslice.kubernetes.io/managed-by: cluster-db.mmoexile.dev
    app.kubernetes.io/part-of: mmoexile
addressType: IPv4
ports: [{ name: $3, port: $4, protocol: TCP }]
endpoints: [{ addresses: ["$2"], conditions: { ready: true } }]
---
END
}

# Removes kind's Docker network once neither a kind cluster nor a database
# container uses it
remove_unused_network() {
  docker network inspect "$DB_NETWORK" >/dev/null 2>&1 || return 0
  [[ -z "$(kind get clusters 2>/dev/null)" ]] || return 0
  [[ "$(docker network inspect -f '{{len .Containers}}' "$DB_NETWORK")" == 0 ]] || return 0
  docker network rm "$DB_NETWORK" >/dev/null && echo "Removed Docker network $DB_NETWORK"
}

# True if PgBouncer (as mmoexile_app) and Redis (as mmoexile) answer over
# verified TLS. Passwords go through the environment, not the arguments.
db_ready() {
  PGPASSWORD=$(secret postgres-app-password) docker exec -e PGPASSWORD "$(db_container postgres)" \
    psql "host=localhost port=6432 dbname=mmoexile user=mmoexile_app sslmode=verify-full sslrootcert=/tls/ca.crt" \
    -tAc "select 1" >/dev/null 2>&1 &&
    REDISCLI_AUTH=$(secret redis-password) docker exec -e REDISCLI_AUTH "$(db_container redis)" \
      redis-cli --tls --cacert /tls/ca.crt -p 6380 --user mmoexile ping 2>/dev/null | grep -q PONG
}

AGONES_CHART_REPO=https://agones.dev/chart/stable
AGONES_VERSION=1.61.0
MONITORING_CHART_REPO=https://prometheus-community.github.io/helm-charts
MONITORING_VERSION=91.9.0  # kube-prometheus-stack

# Apps built from node.Dockerfile (plus the "migrate" and "client" images)
APPS=(account-api social orchestrator directory instance-server)
IMAGE_TAG=dev

# kubectl and helm, always against our cluster (never the current context)
k() { kubectl --context "$CONTEXT" "$@"; }
h() { helm --kube-context "$CONTEXT" "$@"; }

step() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
fail() { printf '\033[31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

cluster_exists() { kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; }

# The kind node (= Docker container) carrying a label, e.g. node_with mmoexile.dev/region=us
node_with() {
  k get nodes -l "$1" -o jsonpath='{.items[0].metadata.name}'
}

image() { echo "mmoexile/$1:$IMAGE_TAG"; }

# Builds one image from the repository: an app, "migrate" or "client"
build_image() {
  local name=$1
  case "$name" in
    client) docker build -q -f "$ROOT/infra/docker/client.Dockerfile" -t "$(image client)" "$ROOT" ;;
    migrate) docker build -q -f "$ROOT/infra/docker/node.Dockerfile" --target migrate -t "$(image migrate)" "$ROOT" ;;
    *) docker build -q -f "$ROOT/infra/docker/node.Dockerfile" --build-arg "APP=$name" -t "$(image "$name")" "$ROOT" ;;
  esac >/dev/null
}

# Loads images into the nodes that run them: load_images <node label> <image>...
# (kind skips images a node already has in the same version)
load_images() {
  local nodes
  nodes=$(k get nodes -l "$1" -o jsonpath='{.items[*].metadata.name}' | tr ' ' ',')
  shift
  kind load docker-image --name "$CLUSTER" --nodes "$nodes" "$@" 2>&1 | grep -vE "not yet present|already present" || true
}
